# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.vehicle import Vehicle  # noqa: F401,E501
from swagger_server import util


class CreateDataRequestVehicle(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, vehicle: Vehicle=None):  # noqa: E501
        """CreateDataRequestVehicle - a model defined in Swagger

        :param vehicle: The vehicle of this CreateDataRequestVehicle.  # noqa: E501
        :type vehicle: Vehicle
        """
        self.swagger_types = {
            'vehicle': Vehicle
        }

        self.attribute_map = {
            'vehicle': 'vehicle'
        }
        self._vehicle = vehicle

    @classmethod
    def from_dict(cls, dikt) -> 'CreateDataRequestVehicle':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateDataRequest_vehicle of this CreateDataRequestVehicle.  # noqa: E501
        :rtype: CreateDataRequestVehicle
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vehicle(self) -> Vehicle:
        """Gets the vehicle of this CreateDataRequestVehicle.


        :return: The vehicle of this CreateDataRequestVehicle.
        :rtype: Vehicle
        """
        return self._vehicle

    @vehicle.setter
    def vehicle(self, vehicle: Vehicle):
        """Sets the vehicle of this CreateDataRequestVehicle.


        :param vehicle: The vehicle of this CreateDataRequestVehicle.
        :type vehicle: Vehicle
        """

        self._vehicle = vehicle
