# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.vehicle import Vehicle  # noqa: F401,E501
from swagger_server import util


class UpdateDataRequestVehicle(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, vehicle: Vehicle=None):  # noqa: E501
        """UpdateDataRequestVehicle - a model defined in Swagger

        :param vehicle: The vehicle of this UpdateDataRequestVehicle.  # noqa: E501
        :type vehicle: Vehicle
        """
        self.swagger_types = {
            'vehicle': Vehicle
        }

        self.attribute_map = {
            'vehicle': 'vehicle'
        }
        self._vehicle = vehicle

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateDataRequestVehicle':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpdateDataRequest_vehicle of this UpdateDataRequestVehicle.  # noqa: E501
        :rtype: UpdateDataRequestVehicle
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vehicle(self) -> Vehicle:
        """Gets the vehicle of this UpdateDataRequestVehicle.


        :return: The vehicle of this UpdateDataRequestVehicle.
        :rtype: Vehicle
        """
        return self._vehicle

    @vehicle.setter
    def vehicle(self, vehicle: Vehicle):
        """Sets the vehicle of this UpdateDataRequestVehicle.


        :param vehicle: The vehicle of this UpdateDataRequestVehicle.
        :type vehicle: Vehicle
        """

        self._vehicle = vehicle
